### ISSUE TITLE
Load config and credentials from a folder instead of directly in /root/

### ISSUE THREAD

**Issue by Enovale** [jackyes/SecureSling#1]
I want to run this container using Kubernetes, which can directly mount individual files but only if I already have the files setup in a dataset, I can't use PVC features which only allows me to mount folders. 

I want the config files to be in a separate folder so I can more easily mount them without hiding the other application files.

**Comment by jackyes** [comment]
Hello, I just made a change: now the app checks if the files `config/config.yaml` and `config/credentials.yaml` exist, if not it uses `config.yaml` and `credentials.yaml`. If I understand your problem correctly, you can now mount the `config` folder in the main root of the app with the configuration files inside

**Comment by DelusionalAI** [comment]
Would It be possible to add the location of those files and the upload folder to an ENV? That way I can mount just one folder with the config .yamls and the temp upload space, or separate it out if I want.

**Comment by jackyes** [comment]
Maybe adding the ability to edit the uploads folder in the config would be enough... In this way you can mount the "config" folder with "config.yaml", "credential.yaml" and the uploads folder, and set the path in the config.yaml to "config/uploads/".

In the next update i Will add this option

**Comment by jackyes** [comment]
> Would It be possible to add the location of those files and the upload folder to an ENV? That way I can mount just one folder with the config .yamls and the temp upload space, or separate it out if I want.

Done, now it is possible to configure in the `config.yaml` where the upload folder is, it is therefore possible to set `UploadDir` in the `config.yaml` to "`./config/uploads`" and mount a folder named `config` with the yamls files and the `uploads` folder
