### ISSUE TITLE
Upload stuck Uploading...

### ISSUE THREAD

**Issue by zarevskaya** [jackyes/SecureSling#2]
Hi, thanks for this cool app!

OS: Debiazn 12 server full updated
Docker + docker-compose full updated
HTTPS => ok
Credentials and config.yaml => ok

I have an issue when I upload a file, he stuck like this:

![Screenshot_20240628_152106](https://github.com/jackyes/SecureSling/assets/60230221/46873419-d4db-4c4a-8f5b-40e7fe29ab9c)

Logs:      

Starting server on port 8080
HTTPS disabled, using HTTP
Starting file upload
Starting file upload
Starting file upload

F12 option in the browser:
Uncaught (in promise) TypeError: xhr.responseText is not a function

chown 1000:1000 -R uploads

Thanks in advance!

**Comment by jackyes** [comment]
Hi! 
I think I understand the problem... In the last docker image uploaded, there is no `uploads` folder (an error of course)... While waiting for the docker image to update, you can fix it with this command:

```
docker exec -it <container_name> mkdir /root/uploads && chown secureslinguser:secureslinggroup /root/uploads
```

**Comment by zarevskaya** [comment]
Thanks jackyes! I'm trying now ;)

**Comment by jackyes** [comment]
I'm uploading the image on dockerhub fixing the "upload" folder issue :)

**Comment by zarevskaya** [comment]
Yeah! That work fine now, thank you very much, I can write my article on your work!

**Comment by jackyes** [comment]
I'm glad it resolved! Wow! I would be happy to read the article!

**Comment by zarevskaya** [comment]
> I'm glad it resolved! Wow! I would be happy to read the article!

I'm going to post it this evening at midnight, I'll let you know but I'm Belgian so it will be in French.

**Comment by jackyes** [comment]
> > I'm glad it resolved! Wow! I would be happy to read the article!
> 
> I'm going to post it this evening at midnight, I'll let you know but I'm Belgian so it will be in French.

Great, I think G translate can help me with this ;)

**Comment by zarevskaya** [comment]
I think too, It's nice to see open source with a neat interface. Is it possible to translate the application?

**Comment by jackyes** [comment]
Thank you!

No translation now...Good idea! I think it will be one of the next additions to SecureSling!

**Comment by zarevskaya** [comment]
> Thank you!
> 
> No translation now...Good idea! I think it will be one of the next additions to SecureSling!

I'd love to be a part of it!

Finally the article is ready!

https://belginux.com/installer-securesling-avec-docker/

**Comment by jackyes** [comment]
**Great**, thanks for the article!

**Comment by zarevskaya** [comment]
You'r welcome, thanks for the support ;)
